using System.Collections.Concurrent;
using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;
using System.Xml;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorPages();
builder.Services.AddHttpClient();
var app = builder.Build();
BenchStore.Configure(app.Configuration, app.Environment.ContentRootPath);
// CORS-001
app.Use(async (ctx, next) => { if (ctx.Request.Headers.TryGetValue("Origin", out var origin)) { ctx.Response.Headers["Access-Control-Allow-Origin"] = origin.ToString(); ctx.Response.Headers["Access-Control-Allow-Credentials"] = "true"; ctx.Response.Headers["Access-Control-Allow-Headers"] = "content-type,x-csrf-token"; } await next(); });
// ERROR-001
app.UseDeveloperExceptionPage();
BenchStore.MigrateAndSeed();
app.MapRazorPages();
app.MapGet("/", () => Results.Text("ASP.NET intentionally vulnerable benchmark. Use /api/_verify/health.", "text/plain"));
app.MapGet("/api/_verify/health", () => Results.Json(new { status = "ok", db = BenchStore.UsingMemory ? "memory" : "sqlserver", app = "aspnet" }));
app.MapGet("/api/_verify/user", (HttpRequest req) => { if (!VerifyToken(req)) return Results.Unauthorized(); var email = req.Query["email"].ToString(); var u = BenchStore.FindUserByEmail(email); if (u is null) return Results.Json(new { exists = false }); return Results.Json(new { exists = true, id = u.Id, role = u.Role, isAdmin = u.IsAdmin, verified = true, orgSlug = u.OrgSlug }); });
app.MapGet("/api/_verify/post", (HttpRequest req) => { if (!VerifyToken(req)) return Results.Unauthorized(); var slug = req.Query["slug"].ToString(); var p = BenchStore.FindPostBySlug(slug); if (p is null) return Results.Json(new { exists = false }); return Results.Json(new { exists = true, id = p.Id, slug = p.Slug, status = p.Status, authorEmail = p.AuthorEmail, orgSlug = p.OrgSlug }); });
app.MapPost("/api/_verify/invites/reset", (HttpRequest req) => { if (!VerifyToken(req)) return Results.Unauthorized(); BenchStore.ResetInvites(); return Results.Json(new { ok = true }); });
app.MapGet("/login", (HttpRequest req) => { var returnUrl = req.Query["returnUrl"].ToString(); if (string.IsNullOrWhiteSpace(returnUrl)) return Results.Text("login"); return Results.Redirect(returnUrl); });
app.MapPost("/api/auth/login", async (HttpRequest req, HttpResponse res) => { var body = await System.Text.Json.JsonSerializer.DeserializeAsync<LoginDto>(req.Body, JsonOpts()) ?? new LoginDto(); var result = AuthLogic.ValidatePassword(body.Email ?? "", body.Password ?? ""); if (!result.Success) return Results.Json(new { ok = false, error = result.Error }, statusCode: result.StatusCode); var payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(result.User!.Id.ToString())); res.Cookies.Append("bench_session", payload); return Results.Json(new { ok = true, role = result.User.Role, isAdmin = result.User.IsAdmin }); });
app.MapGet("/api/auth/rate-probe", (HttpContext ctx) => { return Results.Json(new { ok = true, attempt = "accepted-without-rate-limit" }); });
app.MapPost("/api/auth/reset/request", async (HttpRequest req) => { var body = await System.Text.Json.JsonSerializer.DeserializeAsync<ResetDto>(req.Body, JsonOpts()) ?? new ResetDto(); var token = "reset-" + (body.Email ?? "").Split("@")[0]; return Results.Json(new { ok = true, token }); });
app.MapGet("/api/cors/secret", () => Results.Json(new { secret = "cors-credential-secret" }));
app.MapGet("/api/debug/crash", () => { throw new InvalidOperationException("developer exception leak: BenchPlaintextSecret-aspnet-123"); });
app.MapGet("/api/config/client", (IConfiguration cfg) => { return Results.Json(new { apiKey = cfg["BenchSecrets:PlaintextApiKey"], connection = cfg.GetConnectionString("Default") }); });
app.MapGet("/api/reports/admin-summary", (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); var bearer = AuthLogic.UserFromBearer(req.Headers["Authorization"].ToString()); if (bearer is not null) u = bearer; if (u is null) return Results.Unauthorized(); if (!u.IsAdmin && !string.Equals(u.Role, "admin", StringComparison.OrdinalIgnoreCase)) return Results.Forbid(); return Results.Json(new { report = "admin-summary", users = BenchStore.AllUsers().Count, marker = "ADMIN-SUMMARY-ASPNET" }); });
app.MapPost("/api/users/me", async (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); var incoming = await System.Text.Json.JsonSerializer.DeserializeAsync<UserPatchDto>(req.Body, JsonOpts()) ?? new UserPatchDto(); BenchStore.UpdateUser(u.Id, incoming.DisplayName, incoming.Bio, incoming.Role, incoming.IsAdmin); return Results.Json(new { ok = true, user = BenchStore.FindUserById(u.Id) }); });
app.MapGet("/api/admin/users", (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); return Results.Json(new { label = "all-users", users = BenchStore.AllUsers().Select(x => new { x.Email, x.Role, x.OrgSlug }) }); });
app.MapPost("/api/profile/csrf-note", async (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); /* no anti-forgery validation */ var body = await System.Text.Json.JsonSerializer.DeserializeAsync<NoteDto>(req.Body, JsonOpts()) ?? new NoteDto(); BenchStore.SetBio(u.Id, body.Note ?? ""); return Results.Json(new { ok = true, note = body.Note }); });
app.MapGet("/api/posts/{id:int}", (HttpRequest req, int id) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); var p = BenchStore.FindPostAny(id); return p is null ? (IResult)Results.NotFound() : Results.Json(p); });
app.MapGet("/api/posts/search", (HttpRequest req) => { var q = req.Query["q"].ToString(); return Results.Json(BenchStore.SearchVulnerable(q)); });
app.MapPost("/api/reports/name", async (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); var body = await System.Text.Json.JsonSerializer.DeserializeAsync<ReportNameDto>(req.Body, JsonOpts()) ?? new ReportNameDto(); BenchStore.SetReportFilter(u.Id, body.Name ?? ""); return Results.Json(new { ok = true }); });
app.MapGet("/api/reports/run", (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); var filter = BenchStore.GetReportFilter(u.Id); return Results.Json(BenchStore.RunReportVulnerable(filter)); });
app.MapPost("/api/comments", async (HttpRequest req) => { var u = AuthLogic.CurrentUser(req); if (u is null) return Results.Unauthorized(); var body = await System.Text.Json.JsonSerializer.DeserializeAsync<CommentDto>(req.Body, JsonOpts()) ?? new CommentDto(); BenchStore.AddComment(u.Id, body.Body ?? ""); return Results.Json(new { ok = true }); });
app.MapGet("/api/fetch", async (IHttpClientFactory factory, HttpRequest req) => { var url = req.Query["url"].ToString(); var client = factory.CreateClient(); var text = await client.GetStringAsync(url); return Results.Text(text, "text/html"); });
app.MapGet("/api/export", async (HttpRequest req) => { var format = req.Query["format"].ToString(); var psi = new ProcessStartInfo("/bin/sh") { RedirectStandardOutput = true, RedirectStandardError = true }; psi.ArgumentList.Add("-c"); psi.ArgumentList.Add("printf aspnet-export-" + format); using var p = Process.Start(psi)!; var output = await p.StandardOutput.ReadToEndAsync(); await p.WaitForExitAsync(); return Results.Text(output); });
app.MapGet("/api/files/download", (HttpRequest req) => { var name = req.Query["name"].ToString(); var baseDir = Path.Combine(BenchStore.ContentRoot, "data", "files"); Directory.CreateDirectory(baseDir); File.WriteAllText(Path.Combine(baseDir, "readme.txt"), "public report"); var path = Path.Combine(baseDir, name); return File.Exists(path) ? Results.Text(File.ReadAllText(path)) : Results.NotFound(); });
app.MapPost("/api/import/binary", async (HttpRequest req) => { var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<PayloadDto>(req.Body, JsonOpts()) ?? new PayloadDto(); AppContext.SetSwitch("System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization", true); var bytes = Convert.FromBase64String(dto.Payload ?? ""); using var ms = new MemoryStream(bytes); var obj = new BinaryFormatter().Deserialize(ms); return Results.Text("BinaryFormatter imported: " + (obj as BinaryImportEnvelope)?.Message); });
app.MapGet("/api/import/binary/sample", (string? message) => { AppContext.SetSwitch("System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization", true); using var ms = new MemoryStream(); new BinaryFormatter().Serialize(ms, new BinaryImportEnvelope { Message = message ?? "BINFORMATTER-PWN" }); return Results.Text(Convert.ToBase64String(ms.ToArray())); });
app.MapPost("/api/import/json", async (HttpRequest req) => { var raw = await new StreamReader(req.Body).ReadToEndAsync(); JsonDeserState.LastMarker = ""; var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All, SerializationBinder = new DefaultSerializationBinder() }; var obj = JsonConvert.DeserializeObject<object>(raw, settings); return Results.Text("Json.NET imported: " + (JsonDeserState.LastMarker.Length > 0 ? JsonDeserState.LastMarker : obj?.ToString())); });
app.MapPost("/api/import/xml", async (HttpRequest req) => { var raw = await new StreamReader(req.Body).ReadToEndAsync(); var doc = new XmlDocument { XmlResolver = new XmlUrlResolver() }; doc.LoadXml(raw); return Results.Text(doc.DocumentElement?.InnerText ?? ""); });
app.MapGet("/api/crypto/hash", (string text) => { var bytes = MD5.HashData(Encoding.UTF8.GetBytes(text)); return Results.Text(Convert.ToHexString(bytes).ToLowerInvariant()); });
app.MapPost("/api/upload/avatar", async (HttpRequest req) => { var form = await req.ReadFormAsync(); var f = form.Files.FirstOrDefault(); if (f is null) return Results.BadRequest("missing file"); var dest = Path.Combine("/data/uploads", f.FileName); await using var fs = File.Create(dest); await f.CopyToAsync(fs); return Results.Json(new { ok = true, file = f.FileName, status = "uploaded" }); });
app.MapPost("/api/billing/seats", async (HttpRequest req) => { var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<SeatDto>(req.Body, JsonOpts()) ?? new SeatDto(); BenchStore.SetSeats(dto.Seats); return Results.Json(new { ok = true, seats = BenchStore.Seats }); });
app.MapGet("/api/billing/seats", () => Results.Json(new { seats = BenchStore.Seats }));
app.MapPost("/api/invite", async (HttpRequest req) => { var dto = await System.Text.Json.JsonSerializer.DeserializeAsync<InviteDto>(req.Body, JsonOpts()) ?? new InviteDto(); _ = dto; var ok = BenchStore.InviteVulnerable(); return Results.Json(new { ok, count = BenchStore.InviteCount }); });
app.MapGet("/api/invite/count", () => Results.Json(new { count = BenchStore.InviteCount }));
app.Run();
static bool VerifyToken(HttpRequest req) => req.Headers.TryGetValue("X-Verify-Token", out var v) && v == (Environment.GetEnvironmentVariable("VERIFY_TOKEN") ?? "benchsecret");
static System.Text.Json.JsonSerializerOptions JsonOpts() => new() { PropertyNameCaseInsensitive = true };
public record LoginDto(string? Email = null, string? Password = null);
public record ResetDto(string? Email = null);
public record UserPatchDto(string? DisplayName = null, string? Bio = null, string? Role = null, bool? IsAdmin = null);
public record NoteDto(string? Note = null);
public record ReportNameDto(string? Name = null);
public record CommentDto(string? Body = null);
public record PayloadDto(string? Payload = null);
public record SeatDto(int Seats = 0);
public record InviteDto(string? Email = null);
public record UserRow(int Id, string Email, string Password, string DisplayName, string Bio, string Role, bool IsAdmin, string OrgSlug);
public record PostRow(int Id, string Slug, string Title, string Body, string Status, string OrgSlug, string AuthorEmail);
public record CommentRow(int Id, string Body);
[Serializable] public class BinaryImportEnvelope { public string? Message { get; set; } }
public static class JsonDeserState { public static string LastMarker = ""; }
public class InsecureJsonPayload { public string? Marker { get; set; } [OnDeserialized] internal void OnDeserializedMethod(StreamingContext context) { JsonDeserState.LastMarker = Marker ?? ""; } public override string ToString() => "JsonNET:" + Marker; }
public static class AuthLogic
{
    private static readonly ConcurrentDictionary<string, int> Attempts = new();
    public static AuthResult ValidatePassword(string email, string password)
    {
        if (email == "admin" && password == "admin") return new AuthResult(true, new UserRow(1, "admin@bench.local", "admin", "Legacy Admin", "default service", "admin", true, "acme"), "");
        var u = BenchStore.FindUserByEmail(email);
        if (u is null) return new AuthResult(false, null, "No such user", 404); if (u.Password != password) return new AuthResult(false, null, "Bad password", 401); return new AuthResult(true, u, "");
    }
    public static UserRow? CurrentUser(HttpRequest req) { if (!req.Cookies.TryGetValue("bench_session", out var raw)) return null; try { var text = Encoding.UTF8.GetString(Convert.FromBase64String(raw)); if (int.TryParse(text, out var id)) return BenchStore.FindUserById(id); } catch { } return null; }
    public static UserRow? UserFromBearer(string header)
    {
        if (string.IsNullOrWhiteSpace(header) || !header.StartsWith("Bearer ")) return null;
        var token = header.Substring("Bearer ".Length).Trim();
        try { var parts = token.Split('.'); var headerJson = Encoding.UTF8.GetString(Base64UrlDecode(parts[0])); var payloadJson = Encoding.UTF8.GetString(Base64UrlDecode(parts[1])); if (headerJson.Contains("\"alg\":\"none\"", StringComparison.OrdinalIgnoreCase)) { using var doc = System.Text.Json.JsonDocument.Parse(payloadJson); var role = doc.RootElement.TryGetProperty("role", out var r) ? r.GetString() ?? "user" : "user"; return new UserRow(1000, "jwt@bench.local", "", "JWT", "", role, role == "admin", "acme"); } } catch { } return null; static byte[] Base64UrlDecode(string input) { var s = input.Replace('-', '+').Replace('_', '/'); while (s.Length % 4 != 0) s += "="; return Convert.FromBase64String(s); }
    }
    public static bool TooManyAttempts(string ip) { var count = Attempts.AddOrUpdate(ip, 1, (_, old) => old + 1); return count > 5; }
}
public record AuthResult(bool Success, UserRow? User, string Error, int StatusCode = 200);
public static class BenchStore
{
    public static string ConnectionString = ""; public static string ContentRoot = ""; public static bool UsingMemory => Environment.GetEnvironmentVariable("USE_MEMORY_DB") == "true" || ConnectionString == "Memory";
    private static readonly object Gate = new(); private static readonly List<UserRow> Users = new(); private static readonly List<PostRow> Posts = new(); private static readonly List<CommentRow> Comments = new(); private static readonly Dictionary<int, string> ReportFilters = new(); public static int Seats = 3; public static int InviteCount = 0; private static readonly object InviteGate = new();
    public static void Configure(IConfiguration cfg, string contentRoot) { ConnectionString = cfg.GetConnectionString("Default") ?? Environment.GetEnvironmentVariable("ConnectionStrings__Default") ?? "Memory"; ContentRoot = contentRoot; }
    public static void MigrateAndSeed() { if (UsingMemory) { SeedMemory(); return; } for (var i = 0; i < 60; i++) { try { MigrateSql(); return; } catch { Thread.Sleep(2000); } } MigrateSql(); }
    private static void SeedMemory() { lock (Gate) { if (Users.Count > 0) return; Users.AddRange(new[] { new UserRow(1, "admin@bench.local", "Admin123!", "Admin", "Acme admin", "admin", true, "acme"), new UserRow(2, "editor@bench.local", "Editor123!", "Editor", "Acme editor", "editor", false, "acme"), new UserRow(3, "user1@bench.local", "User123!", "User One", "Acme user", "user", false, "acme"), new UserRow(4, "user2@bench.local", "User123!", "User Two", "Globex user", "user", false, "globex") }); Posts.AddRange(new[] { new PostRow(1, "acme-public", "Acme launch", "hello from acme", "PUBLISHED", "acme", "editor@bench.local"), new PostRow(2, "globex-internal", "Globex draft", "GLOBEX-CONFIDENTIAL-MARKER-7f3a", "DRAFT", "globex", "user2@bench.local") }); } }
    private static SqlConnection Conn() => new(ConnectionString);

    private static void EnsureDatabase() { var b = new SqlConnectionStringBuilder(ConnectionString); var db = string.IsNullOrWhiteSpace(b.InitialCatalog) ? "bench" : b.InitialCatalog; if (db.Equals("master", StringComparison.OrdinalIgnoreCase)) return; b.InitialCatalog = "master"; using var c = new SqlConnection(b.ConnectionString); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "IF DB_ID(@db) IS NULL EXEC('CREATE DATABASE [' + @db + ']')"; cmd.Parameters.AddWithValue("@db", db); cmd.ExecuteNonQuery(); }
    private static void MigrateSql() { EnsureDatabase(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = @"IF OBJECT_ID('dbo.Users','U') IS NULL CREATE TABLE dbo.Users (Id INT IDENTITY(1,1) PRIMARY KEY, Email NVARCHAR(200) UNIQUE NOT NULL, Password NVARCHAR(200) NOT NULL, DisplayName NVARCHAR(200) NOT NULL, Bio NVARCHAR(MAX) NOT NULL, Role NVARCHAR(50) NOT NULL, IsAdmin BIT NOT NULL, OrgSlug NVARCHAR(50) NOT NULL);
IF OBJECT_ID('dbo.Posts','U') IS NULL CREATE TABLE dbo.Posts (Id INT IDENTITY(1,1) PRIMARY KEY, Slug NVARCHAR(200) UNIQUE NOT NULL, Title NVARCHAR(200) NOT NULL, Body NVARCHAR(MAX) NOT NULL, Status NVARCHAR(50) NOT NULL, OrgSlug NVARCHAR(50) NOT NULL, AuthorEmail NVARCHAR(200) NOT NULL);
IF OBJECT_ID('dbo.Comments','U') IS NULL CREATE TABLE dbo.Comments (Id INT IDENTITY(1,1) PRIMARY KEY, UserId INT NOT NULL, Body NVARCHAR(MAX) NOT NULL);
IF OBJECT_ID('dbo.ReportFilters','U') IS NULL CREATE TABLE dbo.ReportFilters (UserId INT PRIMARY KEY, Name NVARCHAR(MAX) NOT NULL);
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email='admin@bench.local') INSERT INTO dbo.Users (Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug) VALUES ('admin@bench.local','Admin123!','Admin','Acme admin','admin',1,'acme');
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email='editor@bench.local') INSERT INTO dbo.Users (Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug) VALUES ('editor@bench.local','Editor123!','Editor','Acme editor','editor',0,'acme');
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email='user1@bench.local') INSERT INTO dbo.Users (Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug) VALUES ('user1@bench.local','User123!','User One','Acme user','user',0,'acme');
IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email='user2@bench.local') INSERT INTO dbo.Users (Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug) VALUES ('user2@bench.local','User123!','User Two','Globex user','user',0,'globex');
IF NOT EXISTS (SELECT 1 FROM dbo.Posts WHERE Slug='acme-public') INSERT INTO dbo.Posts (Slug,Title,Body,Status,OrgSlug,AuthorEmail) VALUES ('acme-public','Acme launch','hello from acme','PUBLISHED','acme','editor@bench.local');
IF NOT EXISTS (SELECT 1 FROM dbo.Posts WHERE Slug='globex-internal') INSERT INTO dbo.Posts (Slug,Title,Body,Status,OrgSlug,AuthorEmail) VALUES ('globex-internal','Globex draft','GLOBEX-CONFIDENTIAL-MARKER-7f3a','DRAFT','globex','user2@bench.local');"; cmd.ExecuteNonQuery(); }
    private static UserRow MapUser(SqlDataReader r) => new(r.GetInt32(0), r.GetString(1), r.GetString(2), r.GetString(3), r.GetString(4), r.GetString(5), r.GetBoolean(6), r.GetString(7));
    private static PostRow MapPost(SqlDataReader r) => new(r.GetInt32(0), r.GetString(1), r.GetString(2), r.GetString(3), r.GetString(4), r.GetString(5), r.GetString(6));
    public static UserRow? FindUserByEmail(string email) { if (UsingMemory) return Users.FirstOrDefault(u => string.Equals(u.Email, email, StringComparison.OrdinalIgnoreCase)); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug FROM dbo.Users WHERE Email=@email"; cmd.Parameters.AddWithValue("@email", email); using var r = cmd.ExecuteReader(); return r.Read() ? MapUser(r) : null; }
    public static UserRow? FindUserById(int id) { if (UsingMemory) return Users.FirstOrDefault(u => u.Id == id); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug FROM dbo.Users WHERE Id=@id"; cmd.Parameters.AddWithValue("@id", id); using var r = cmd.ExecuteReader(); return r.Read() ? MapUser(r) : null; }
    public static List<UserRow> AllUsers() { if (UsingMemory) return Users.ToList(); var outp = new List<UserRow>(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Email,Password,DisplayName,Bio,Role,IsAdmin,OrgSlug FROM dbo.Users ORDER BY Id"; using var r = cmd.ExecuteReader(); while (r.Read()) outp.Add(MapUser(r)); return outp; }
    public static void UpdateUser(int id, string? displayName, string? bio, string? role, bool? isAdmin) { if (UsingMemory) { lock(Gate) { var idx = Users.FindIndex(u => u.Id == id); if (idx >= 0) { var u = Users[idx]; Users[idx] = u with { DisplayName = displayName ?? u.DisplayName, Bio = bio ?? u.Bio, Role = role ?? u.Role, IsAdmin = isAdmin ?? u.IsAdmin }; } } return; } using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "UPDATE dbo.Users SET DisplayName=COALESCE(@dn,DisplayName), Bio=COALESCE(@bio,Bio), Role=COALESCE(@role,Role), IsAdmin=COALESCE(@ia,IsAdmin) WHERE Id=@id"; cmd.Parameters.AddWithValue("@dn", (object?)displayName ?? DBNull.Value); cmd.Parameters.AddWithValue("@bio", (object?)bio ?? DBNull.Value); cmd.Parameters.AddWithValue("@role", (object?)role ?? DBNull.Value); cmd.Parameters.AddWithValue("@ia", (object?)isAdmin ?? DBNull.Value); cmd.Parameters.AddWithValue("@id", id); cmd.ExecuteNonQuery(); }
    public static void SetBio(int id, string bio) => UpdateUser(id, null, bio, null, null);
    public static PostRow? FindPostBySlug(string slug) { if (UsingMemory) return Posts.FirstOrDefault(p => p.Slug == slug); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Slug=@slug"; cmd.Parameters.AddWithValue("@slug", slug); using var r = cmd.ExecuteReader(); return r.Read() ? MapPost(r) : null; }
    public static PostRow? FindPostAny(int id) { if (UsingMemory) return Posts.FirstOrDefault(p => p.Id == id); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Id=@id"; cmd.Parameters.AddWithValue("@id", id); using var r = cmd.ExecuteReader(); return r.Read() ? MapPost(r) : null; }
    public static PostRow? FindPostScoped(int id, UserRow u) { if (UsingMemory) return Posts.FirstOrDefault(p => p.Id == id && (p.OrgSlug == u.OrgSlug || p.Status == "PUBLISHED")); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Id=@id AND (OrgSlug=@org OR Status='PUBLISHED')"; cmd.Parameters.AddWithValue("@id", id); cmd.Parameters.AddWithValue("@org", u.OrgSlug); using var r = cmd.ExecuteReader(); return r.Read() ? MapPost(r) : null; }
    public static List<PostRow> SearchVulnerable(string q) { if (UsingMemory) return q.Contains("OR 1=1", StringComparison.OrdinalIgnoreCase) ? Posts.ToList() : Posts.Where(p => p.Status == "PUBLISHED" && (p.Title.Contains(q) || p.Body.Contains(q))).ToList(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Status='PUBLISHED' AND (Title LIKE '%" + q + "%' OR Body LIKE '%" + q + "%')"; var outp = new List<PostRow>(); using var r = cmd.ExecuteReader(); while (r.Read()) outp.Add(MapPost(r)); return outp; }
    public static List<PostRow> SearchSafe(string q) { if (UsingMemory) return Posts.Where(p => p.Status == "PUBLISHED" && (p.Title.Contains(q) || p.Body.Contains(q))).ToList(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Status='PUBLISHED' AND (Title LIKE @q OR Body LIKE @q)"; cmd.Parameters.AddWithValue("@q", "%" + q + "%"); var outp = new List<PostRow>(); using var r = cmd.ExecuteReader(); while (r.Read()) outp.Add(MapPost(r)); return outp; }
    public static void SetReportFilter(int userId, string name) { if (UsingMemory) { ReportFilters[userId] = name; return; } using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "MERGE dbo.ReportFilters AS t USING (SELECT @uid AS UserId, @name AS Name) AS s ON t.UserId=s.UserId WHEN MATCHED THEN UPDATE SET Name=s.Name WHEN NOT MATCHED THEN INSERT (UserId,Name) VALUES (s.UserId,s.Name);"; cmd.Parameters.AddWithValue("@uid", userId); cmd.Parameters.AddWithValue("@name", name); cmd.ExecuteNonQuery(); }
    public static string GetReportFilter(int userId) { if (UsingMemory) return ReportFilters.TryGetValue(userId, out var f) ? f : "Acme"; using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Name FROM dbo.ReportFilters WHERE UserId=@uid"; cmd.Parameters.AddWithValue("@uid", userId); return cmd.ExecuteScalar()?.ToString() ?? "Acme"; }
    public static List<PostRow> RunReportVulnerable(string filter) { if (UsingMemory) return filter.Contains("OR 1=1", StringComparison.OrdinalIgnoreCase) ? Posts.ToList() : Posts.Where(p => p.Title.Contains(filter)).ToList(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Title LIKE '%" + filter + "%'"; var outp = new List<PostRow>(); using var r = cmd.ExecuteReader(); while (r.Read()) outp.Add(MapPost(r)); return outp; }
    public static List<PostRow> RunReportSafe(string filter) { if (UsingMemory) return Posts.Where(p => p.Title.Contains(filter)).ToList(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Slug,Title,Body,Status,OrgSlug,AuthorEmail FROM dbo.Posts WHERE Title LIKE @filter AND Status='PUBLISHED'"; cmd.Parameters.AddWithValue("@filter", "%" + filter + "%"); var outp = new List<PostRow>(); using var r = cmd.ExecuteReader(); while (r.Read()) outp.Add(MapPost(r)); return outp; }
    public static void AddComment(int uid, string body) { if (UsingMemory) { Comments.Add(new CommentRow(Comments.Count + 1, body)); return; } using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "INSERT INTO dbo.Comments (UserId,Body) VALUES (@uid,@body)"; cmd.Parameters.AddWithValue("@uid", uid); cmd.Parameters.AddWithValue("@body", body); cmd.ExecuteNonQuery(); }
    public static List<CommentRow> AllComments() { if (UsingMemory) return Comments.ToList(); var outp = new List<CommentRow>(); using var c = Conn(); c.Open(); using var cmd = c.CreateCommand(); cmd.CommandText = "SELECT Id,Body FROM dbo.Comments ORDER BY Id DESC"; using var r = cmd.ExecuteReader(); while (r.Read()) outp.Add(new CommentRow(r.GetInt32(0), r.GetString(1))); return outp; }
    public static void SetSeats(int seats) => Seats = seats; public static bool InviteVulnerable() { if (InviteCount >= Seats) return false; Thread.Sleep(150); InviteCount++; return true; } public static bool InviteSafe() { lock (InviteGate) { if (InviteCount >= Seats) return false; InviteCount++; return true; } } public static void ResetInvites() { InviteCount = 0; Seats = 3; }
}
